
services:
  db:
    image: postgres
    container_name: polling-system-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data